kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: smackweb-deploy
spec:
  replicas: 2
  template: 
    metadata:
      labels:
        app: smackweb
    spec:
      imagePullSecrets:
      - name: dockerregistrysecret
      containers:
      - name: smackweb
        image: tstraubk8shackfest.azurecr.io/smackweb
        env:
        - name: API_SERVICE
          value: "smackapi.default.svc.cluster.local"
        - name: API_PORT
          value: "8081"
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: smackweb
spec:
  selector:
    app: smackweb
  type: LoadBalancer  
  ports:
  - name: http
    port: 8080
    targetPort: 8080